### ISSUE TITLE
Android 6 support

### ISSUE THREAD

**Issue by VladSumtsov** [ks3sdk/KSYLiveAndroidSDK#14]
I catch this exception on android 6+. On android 5.1 and less, everything works fine. 

E/MediaRecorder: start failed: -2147483648
W/System.err: java.lang.RuntimeException: start failed.
W/System.err:     at android.media.MediaRecorder.start(Native Method)
W/System.err:     at com.ksy.recordlib.service.recoder.RecoderVideoSource.prepare(RecoderVideoSource.java:105)
W/System.err:     at com.ksy.recordlib.service.recoder.RecoderVideoSource.run(RecoderVideoSource.java:173)
W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by tian9246** [comment]
yeah it may be support in software encoding

**Comment by VladSumtsov** [comment]
I found, that reason of the crash is output in RecoderVideoSource class
Strange, that it doesn't work, only for android 6
    
`try {
    this.piple = ParcelFileDescriptor.createPipe();
 } catch (IOException e) {
    e.printStackTrace();
 }
 recorder.setOutputFile(this.piple[1].getFileDescriptor());

**Comment by tian9246** [comment]
yeah i know the reason  maybe socket FD will be work but not try thx

**Comment by Asif00** [comment]
I have the same problem, I'm testing on Nexus 7 API 23.  Lower APIs work fine.

**Comment by VladSumtsov** [comment]
I change pipe to two separate streams, seems it works fine.

**Comment by Asif00** [comment]
Thanks Vlad, I ended up changing libraries but good to know.

**Comment by CrazyDude1994** [comment]
@VladSumtsov can you provide more info about the fix? Source code examples is a plus

**Comment by VladSumtsov** [comment]
@CrazyDude1994 https://gist.github.com/VladSumtsov/4a3dc5ca3c569c5741cb

**Comment by CrazyDude1994** [comment]
@VladSumtsov Thanks! I'm really appreciate this!
