### ISSUE TITLE
为什么设置视频大小就报错！

### ISSUE THREAD

**Issue by xiaoyuanandroid** [ks3sdk/KSYLiveAndroidSDK#16]
在KsyRecordClientConfig下面 
if (mVideoWidth > 0 && mVideoHeight > 0) {
      mediaRecorder.setVideoSize(800, 450);设置这个大小就报错，设置720，480大小就不报错，为什么？
        }

 Process: com.ksy.ksyrecordsdk, PID: 31909
    java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
            at android.os.Handler.<init>(Handler.java:200)
            at android.os.Handler.<init>(Handler.java:114)
            at android.widget.Toast$TN.<init>(Toast.java:345)
            at android.widget.Toast.<init>(Toast.java:100)
            at android.widget.Toast.makeText(Toast.java:256)
            at com.ksy.ksyrecordsdk.MainActivity.onClientError(MainActivity.java:394)
            at com.ksy.recordlib.service.core.KsyRecordClient.onClientError(KsyRecordClient.java:119)
            at com.ksy.recordlib.service.recoder.RecoderVideoTempSource.prepare(RecoderVideoTempSource.java:66)
            at com.ksy.recordlib.service.recoder.RecoderVideoTempSource.run(RecoderVideoTempSource.java:165)
            at java.lang.Thread.run(Thread.java:841)
同意都是大小，设置800，450就出这个错误！！！

**Comment by xiaoyuanandroid** [comment]
请前辈帮看看！

**Comment by wnpllrzodiac** [comment]
摄像头的尺寸是固定的吧。不是任意分辨率都支持的。你应该先查询摄像头支持哪些分辨率，再设置。
