### ISSUE TITLE
禁用录音权限的情况下，会崩溃

### ISSUE THREAD

**Issue by lsjwzh** [ks3sdk/KSYLiveAndroidSDK#7]
机型：GIONEE GN9007  api22
java.lang.RuntimeException: setAudioSource failed.
                                                       at android.media.MediaRecorder.setAudioSource(Native Method)
                                                       at com.ksy.recordlib.service.recoder.RecoderAudioSource.prepare(RecoderAudioSource.java:88)
                                                       at com.ksy.recordlib.service.recoder.RecoderAudioSource.run(RecoderAudioSource.java:149)
                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by tian9246** [comment]
we have to use audio data as clock reference so if can't use mic it would be stop by new logic
